# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160330_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
